stages:
  - test

default:
  image: python:3.11-slim
  # tags: ["docker"]  # Put here tags that makes sense for the GitLab setup
  artifacts:
    expire_in: 1 days
  retry:
    max: 2
    when:
    - runner_system_failure
  interruptible: true

.python:
  extends: default
  before_script:
    - pip install poetry tox
    - poetry config virtualenvs.in-project true
    - poetry install
    - source `poetry env info --path`/bin/activate
  cache:
    key: ".python"
    paths:
      - .mypy_cache
      - .pytest_cache
      - .tox
      - .venv

test:
  extends: .python
  stage: test
  script:
    - tox
